<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── T-Shirts ──────────────────────────────────────────────────────
            [
                'sku'              => 'TSH-001',
                'brand'            => 'Urban Basics',
                'name'             => 'Classic Black Cotton T-Shirt',
                'description'      => 'A premium quality black cotton t-shirt perfect for everyday casual wear. Soft, breathable fabric with a relaxed fit.',
                'category'         => 'casual clothing',
                'color'            => 'black',
                'available_colors' => ['black', 'white', 'grey'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 19.99,
                'tags'             => ['t-shirt', 'casual', 'cotton', 'black', 'everyday', 'unisex'],
                'popularity'       => 95,
            ],
            [
                'sku'              => 'TSH-002',
                'brand'            => 'StreetEdge',
                'name'             => 'Graphic Print White T-Shirt',
                'description'      => 'Trendy white graphic tee with modern print design. Great for young adults who love street style.',
                'category'         => 'casual clothing',
                'color'            => 'white',
                'available_colors' => ['white', 'black'],
                'size'             => 'M',
                'available_sizes'  => ['XS', 'S', 'M', 'L', 'XL'],
                'price'            => 24.99,
                'tags'             => ['t-shirt', 'graphic', 'white', 'street style', 'trendy', 'youth'],
                'popularity'       => 80,
            ],
            [
                'sku'              => 'TSH-003',
                'brand'            => 'EcoWear',
                'name'             => 'Navy Blue Basic T-Shirt',
                'description'      => 'Simple navy blue t-shirt made from 100% organic cotton. Versatile and comfortable for all-day wear.',
                'category'         => 'casual clothing',
                'color'            => 'navy blue',
                'available_colors' => ['navy blue', 'white', 'green'],
                'size'             => 'S',
                'available_sizes'  => ['XS', 'S', 'M', 'L'],
                'price'            => 17.99,
                'tags'             => ['t-shirt', 'navy', 'organic', 'basic', 'casual', 'comfortable'],
                'popularity'       => 70,
            ],

            // ── Hoodies ───────────────────────────────────────────────────────
            [
                'sku'              => 'HDY-001',
                'brand'            => 'UrbanEdge',
                'name'             => 'Black Oversized Hoodie',
                'description'      => 'Stylish oversized black hoodie with kangaroo pocket. Perfect for 20s crowd who love streetwear and urban fashion.',
                'category'         => 'casual clothing',
                'color'            => 'black',
                'available_colors' => ['black', 'grey', 'white'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 49.99,
                'tags'             => ['hoodie', 'oversized', 'black', 'streetwear', 'urban', 'youth', 'kangaroo pocket'],
                'popularity'       => 100,
            ],
            [
                'sku'              => 'HDY-002',
                'brand'            => 'CozyWear',
                'name'             => 'Grey Pullover Hoodie',
                'description'      => 'Classic grey pullover hoodie with fleece lining. Great for cool weather and casual outings.',
                'category'         => 'casual clothing',
                'color'            => 'grey',
                'available_colors' => ['grey', 'navy blue', 'black'],
                'size'             => 'XL',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 44.99,
                'tags'             => ['hoodie', 'pullover', 'grey', 'fleece', 'warm', 'casual'],
                'popularity'       => 85,
            ],
            [
                'sku'              => 'HDY-003',
                'brand'            => 'BoldWear',
                'name'             => 'Red Zip-Up Hoodie',
                'description'      => 'Vibrant red zip-up hoodie with two side pockets. Casual yet stylish for everyday wear.',
                'category'         => 'casual clothing',
                'color'            => 'red',
                'available_colors' => ['red', 'blue', 'black'],
                'size'             => 'M',
                'available_sizes'  => ['XS', 'S', 'M', 'L', 'XL'],
                'price'            => 52.99,
                'tags'             => ['hoodie', 'zip-up', 'red', 'casual', 'pockets', 'stylish'],
                'popularity'       => 72,
            ],

            // ── Formal Wear ───────────────────────────────────────────────────
            [
                'sku'              => 'FRM-001',
                'brand'            => 'EliteFormal',
                'name'             => 'Premium Black Formal Blazer',
                'description'      => 'Elegant black formal blazer crafted from high-quality wool blend. Perfect for business meetings, events, and formal occasions.',
                'category'         => 'formal wear',
                'color'            => 'black',
                'available_colors' => ['black', 'charcoal', 'navy'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 129.99,
                'tags'             => ['blazer', 'formal', 'black', 'wool', 'business', 'elegant', 'premium'],
                'popularity'       => 88,
            ],
            [
                'sku'              => 'FRM-002',
                'brand'            => 'EliteFormal',
                'name'             => 'Navy Blue Slim Fit Suit',
                'description'      => 'Modern slim-fit navy blue suit with fine Italian fabric. Ideal for weddings, interviews, and corporate events.',
                'category'         => 'formal wear',
                'color'            => 'navy blue',
                'available_colors' => ['navy blue', 'charcoal', 'black'],
                'size'             => 'M',
                'available_sizes'  => ['S', 'M', 'L', 'XL'],
                'price'            => 249.99,
                'tags'             => ['suit', 'formal', 'navy', 'slim fit', 'Italian', 'wedding', 'interview'],
                'popularity'       => 76,
            ],
            [
                'sku'              => 'FRM-003',
                'brand'            => 'ClassicStyle',
                'name'             => 'White Formal Dress Shirt',
                'description'      => 'Crisp white formal dress shirt with French cuffs. Pairs beautifully with suits and blazers.',
                'category'         => 'formal wear',
                'color'            => 'white',
                'available_colors' => ['white', 'light blue', 'cream'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 39.99,
                'tags'             => ['dress shirt', 'formal', 'white', 'business', 'French cuffs', 'crisp'],
                'popularity'       => 82,
            ],

            // ── Jeans & Pants ─────────────────────────────────────────────────
            [
                'sku'              => 'DNM-001',
                'brand'            => 'DenimCo',
                'name'             => 'Slim Fit Black Jeans',
                'description'      => 'Modern slim-fit black jeans made from stretch denim. Versatile for both casual and semi-formal occasions.',
                'category'         => 'casual clothing',
                'color'            => 'black',
                'available_colors' => ['black', 'dark grey'],
                'size'             => 'L',
                'available_sizes'  => ['28', '30', '32', '34', '36'],
                'price'            => 59.99,
                'tags'             => ['jeans', 'slim fit', 'black', 'denim', 'stretch', 'casual', 'versatile'],
                'popularity'       => 90,
            ],
            [
                'sku'              => 'DNM-002',
                'brand'            => 'DenimCo',
                'name'             => 'Classic Blue Straight Jeans',
                'description'      => 'Timeless blue straight-cut jeans with classic 5-pocket design. A wardrobe staple for any age.',
                'category'         => 'casual clothing',
                'color'            => 'blue',
                'available_colors' => ['blue', 'light blue', 'black'],
                'size'             => 'M',
                'available_sizes'  => ['28', '30', '32', '34', '36'],
                'price'            => 54.99,
                'tags'             => ['jeans', 'straight cut', 'blue', 'denim', 'classic', 'staple', '5-pocket'],
                'popularity'       => 88,
            ],
            [
                'sku'              => 'PNT-001',
                'brand'            => 'SmartFit',
                'name'             => 'Khaki Chino Pants',
                'description'      => 'Smart khaki chino pants with a slim tapered fit. Perfect for smart-casual dress codes.',
                'category'         => 'casual clothing',
                'color'            => 'khaki',
                'available_colors' => ['khaki', 'navy', 'olive'],
                'size'             => 'M',
                'available_sizes'  => ['28', '30', '32', '34', '36'],
                'price'            => 44.99,
                'tags'             => ['chinos', 'khaki', 'slim', 'smart-casual', 'pants', 'office casual'],
                'popularity'       => 65,
            ],

            // ── Jackets ───────────────────────────────────────────────────────
            [
                'sku'              => 'JKT-001',
                'brand'            => 'UrbanEdge',
                'name'             => 'Black Leather Biker Jacket',
                'description'      => 'Edgy black faux-leather biker jacket with multiple zippers. A bold statement piece for youth fashion.',
                'category'         => 'casual clothing',
                'color'            => 'black',
                'available_colors' => ['black', 'brown'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL'],
                'price'            => 89.99,
                'tags'             => ['jacket', 'leather', 'biker', 'black', 'edgy', 'streetwear', 'fashion', 'bold'],
                'popularity'       => 93,
            ],
            [
                'sku'              => 'JKT-002',
                'brand'            => 'OutdoorPro',
                'name'             => 'Olive Green Parka Jacket',
                'description'      => 'Warm olive green parka with detachable faux-fur hood. Ideal for cold weather outdoor activities.',
                'category'         => 'outerwear',
                'color'            => 'olive green',
                'available_colors' => ['olive green', 'black', 'navy'],
                'size'             => 'XL',
                'available_sizes'  => ['S', 'M', 'L', 'XL', 'XXL'],
                'price'            => 99.99,
                'tags'             => ['parka', 'jacket', 'olive', 'warm', 'winter', 'outdoor', 'hooded'],
                'popularity'       => 78,
            ],

            // ── Shoes ─────────────────────────────────────────────────────────
            [
                'sku'              => 'SHO-001',
                'brand'            => 'ClassicStep',
                'name'             => 'Black Leather Oxford Shoes',
                'description'      => 'Classic black leather Oxford shoes with a sleek, polished finish. Essential for formal and business attire.',
                'category'         => 'shoes',
                'color'            => 'black',
                'available_colors' => ['black', 'brown', 'tan'],
                'size'             => '42',
                'available_sizes'  => ['40', '41', '42', '43', '44', '45'],
                'price'            => 79.99,
                'tags'             => ['shoes', 'oxford', 'leather', 'black', 'formal', 'classic', 'business'],
                'popularity'       => 85,
            ],
            [
                'sku'              => 'SHO-002',
                'brand'            => 'Nike',
                'name'             => 'White Canvas Sneakers',
                'description'      => 'Clean white canvas sneakers with rubber sole. Minimalist design perfect for casual everyday outfits.',
                'category'         => 'shoes',
                'color'            => 'white',
                'available_colors' => ['white', 'black', 'grey'],
                'size'             => '42',
                'available_sizes'  => ['38', '39', '40', '41', '42', '43', '44'],
                'price'            => 34.99,
                'tags'             => ['sneakers', 'canvas', 'white', 'casual', 'minimalist', 'everyday'],
                'popularity'       => 95,
            ],
            [
                'sku'              => 'SHO-003',
                'brand'            => 'Nike',
                'name'             => 'Black Running Sneakers',
                'description'      => 'Lightweight black running sneakers with air-cushion sole and breathable mesh upper. Great for sports and active lifestyle.',
                'category'         => 'shoes',
                'color'            => 'black',
                'available_colors' => ['black', 'white', 'red'],
                'size'             => '44',
                'available_sizes'  => ['40', '41', '42', '43', '44', '45'],
                'price'            => 64.99,
                'tags'             => ['sneakers', 'running', 'black', 'sports', 'athletic', 'breathable', 'cushioned'],
                'popularity'       => 92,
            ],

            // ── Accessories ───────────────────────────────────────────────────
            [
                'sku'              => 'ACC-001',
                'brand'            => 'LeatherCraft',
                'name'             => 'Black Leather Belt',
                'description'      => 'Premium black genuine leather belt with a polished silver buckle. Suitable for both casual and formal use.',
                'category'         => 'accessories',
                'color'            => 'black',
                'available_colors' => ['black', 'brown', 'tan'],
                'size'             => 'L',
                'available_sizes'  => ['S', 'M', 'L', 'XL'],
                'price'            => 24.99,
                'tags'             => ['belt', 'leather', 'black', 'accessories', 'silver buckle', 'formal', 'casual'],
                'popularity'       => 70,
            ],
            [
                'sku'              => 'ACC-002',
                'brand'            => 'StreetEdge',
                'name'             => 'Classic Black Snapback Cap',
                'description'      => 'Trendy black snapback baseball cap with embroidered logo. Popular among young adults and streetwear fans.',
                'category'         => 'accessories',
                'color'            => 'black',
                'available_colors' => ['black', 'white', 'red', 'navy'],
                'size'             => 'one size',
                'available_sizes'  => ['one size'],
                'price'            => 19.99,
                'tags'             => ['cap', 'snapback', 'black', 'baseball', 'streetwear', 'youth', 'trendy'],
                'popularity'       => 85,
            ],
            [
                'sku'              => 'ACC-003',
                'brand'            => 'WoolLux',
                'name'             => 'Grey Wool Scarf',
                'description'      => 'Soft grey wool scarf ideal for autumn and winter. Adds a stylish touch to any outfit.',
                'category'         => 'accessories',
                'color'            => 'grey',
                'available_colors' => ['grey', 'black', 'cream', 'burgundy'],
                'size'             => 'one size',
                'available_sizes'  => ['one size'],
                'price'            => 22.99,
                'tags'             => ['scarf', 'wool', 'grey', 'winter', 'warm', 'accessories', 'stylish'],
                'popularity'       => 55,
            ],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }

        $this->command->info('Seeded ' . count($products) . ' products successfully.');
    }
}
